name: run-flake
description: run flake8

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: python -m pip install -r requirements_lint.txt

    - name: Lint with flake8
      shell: bash
      run: flake8 . --count --show-source --statistics
