name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run flake
        uses: ./.github/actions/run-flake

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run isort
        uses: ./.github/actions/run-isort

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: black
        uses: psf/black@stable
        with:
          version: "22.12.0"

  common-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Common tests
        uses: ./.github/actions/common-tests

      # - name: upload to codecov binary
      #   run: |
      #     curl --silent --show-error --output codecov https://uploader.codecov.io/latest/linux/codecov
      #     chmod +x codecov
      #     ./codecov --file coverage.xml --flags unittests-${{ matrix.python-version }}

      - name: "Upload to Codecov"
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests-${{ matrix.python-version }}
          name: codecov-umbrella
          verbose: true
          # token: "${{ secrets.CODECOV_TOKEN }}"
