name: Build container image

on:
  push:
    branches:
      - "main"

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      QUAY_PASSWORD: ${{ secrets.EDA_AIZQUIERDO_QUAY_PW }}
      QUAY_USERNAME: "aizquier+edaci"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t ansible-rulebook:latest . --no-cache

      - name: Tag image
        run: >
          docker image tag ansible-rulebook:latest
          quay.io/aizquier/ansible-rulebook:latest

      - name: Push image
        run: |
          docker login -u=$QUAY_USERNAME -p=$QUAY_PASSWORD quay.io
          docker image push quay.io/aizquier/ansible-events:latest
