name: scheduled

on:
  schedule:
    # Run at 10:00 AM/PM UTC
    - cron: "0 10,22 * * *"
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run flake
        uses: ./.github/actions/run-flake

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run isort
        uses: ./.github/actions/run-isort

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: black
        uses: psf/black@stable
        with:
          version: "22.12.0"

  common-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: All tests
        uses: ./.github/actions/all-tests

      - name: Upload coverage to Codecov
        uses: ./.github/actions/upload-to-codecov

      # WAITING FOR APPROVAL

      # - name: Notify to slack if failure
      #   if: ${{ failure() }}
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_MESSAGE: Failure of scheduled executed tests for ansible rulebook
