name: "Test Report"
on:
  workflow_run:
    workflows:
      - "ci" # runs after ci workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        id: Test Report # Set ID reference for step
        with:
          artifact: test-results # artifact name
          name: common-tests
          path: test-report.xml
          reporter: java-junit
